/* -*- fill-column: 77; c-basic-offset: 4; -*- */
/* 
 * Copyright 2006 by Eric House (xwords@eehouse.org).  All rights reserved.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 *
 * Derived from code generated by M$'s eVC++.
 */


#ifndef _DEBHACKS_H_
#define _DEBHACKS_H_

#ifdef USE_DEB_HACKS

#define MS(func) M$_##func
#define DH(func) debhack_##func


typedef struct DH(WIN32_FIND_DATA) {
	DWORD dwFileAttributes;
	FILETIME dh_ftCreationTime;
	FILETIME dh_ftLastAccessTime;
	FILETIME dh_ftLastWriteTime;
	DWORD dh_nFileSizeHigh;
	DWORD dh_nFileSizeLow;
	DWORD dh_dwReserved1;
	WCHAR cFileName[MAX_PATH];
} DH(WIN32_FIND_DATA);

wchar_t* DH(lstrcat)(wchar_t *s1, const wchar_t* s2);
wchar_t* DH(lstrcpy)(wchar_t* dest, const wchar_t* src);
int DH(DialogBoxParam)( HINSTANCE hinst, LPCWSTR str, HWND hwnd, 
                            DLGPROC proc, LPARAM lparam );
BOOL DH(GetTextExtentPoint32)( HDC,LPCWSTR,int,LPSIZE);
DWORD DH(GetCurrentThreadId)(void);
BOOL DH(SetEvent)(HANDLE);
BOOL DH(ResetEvent)(HANDLE);

LRESULT debhack_CommandBar_InsertButton(HWND hwnd, WPARAM button, 
                                        LPARAM lparam );
void debhack_CommandBar_Destroy( HWND hwnd );

#else

#define MS(func) func
#define DH(func) func

#endif

#endif
