/*
 * Copyright 2025 by Eric House (xwords@eehouse.org).  All rights reserved.
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the Free
 * Software Foundation; either version 2 of the License, or (at your option)
 * any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc., 59
 * Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 *
 * This file was largely generated by github copilot.
 */
#ifdef PLATFORM_NCURSES

#include "cursqr.h"
#include "dbgutil.h"

#include <ncurses.h>
#include <qrencode.h>
#include <string.h>

/* Display QR code in full-screen dialog */
void
cursesShowQRDialog( const char* text, const char* title )
{
    WINDOW* dialog = NULL;
    QRcode* qrCode = NULL;
    int terminalHeight, terminalWidth;
    int dialogHeight, dialogWidth;
    int startRow, startCol;
    int qrStartRow, qrStartCol;
    int titleRow, urlRow;
    int qrDataRow, qrDataCol;
    unsigned char qrModule;
    const char* instructions = "Press any key to close";
    if ( !!text && text[0] != '\0' ) {
        qrCode = QRcode_encodeString( text, 0, QR_ECLEVEL_L, QR_MODE_8, 1 );
    }
    if ( !!qrCode ) {
        getmaxyx( stdscr, terminalHeight, terminalWidth );
        dialogHeight = terminalHeight - 2;
        dialogWidth = terminalWidth - 2;
        startRow = 1;
        startCol = 1;
        dialog = newwin( dialogHeight, dialogWidth, startRow, startCol );
        if ( !!dialog ) {
            box( dialog, 0, 0 );
            titleRow = 1;
            if ( !!title && title[0] != '\0' ) {
                mvwaddstr( dialog, titleRow, (dialogWidth - strlen(title)) / 2, title );
            }
            qrStartRow = (dialogHeight - qrCode->width - 4) / 2;
            qrStartCol = (dialogWidth - (qrCode->width * 2) - 4) / 2;
            for ( int moduleRow = 0; moduleRow < qrCode->width + 4; ++moduleRow ) {
                for ( int moduleCol = 0; moduleCol < qrCode->width * 2 + 4; moduleCol += 2 ) {
                    qrDataRow = moduleRow - 2;
                    qrDataCol = (moduleCol - 4) / 2;
                    int thisRow = qrStartRow + moduleRow;
                    int thisCol = qrStartCol + moduleCol;
                    if ( qrDataRow < 0 || qrDataRow >= qrCode->width || qrDataCol < 0 || qrDataCol >= qrCode->width ) {
                        mvwaddstr( dialog, thisRow, thisCol, "  " );
                    } else {
                        qrModule = qrCode->data[qrDataRow * qrCode->width + qrDataCol];
                        if ( qrModule & 1 ) {
                            wattron( dialog, A_REVERSE );
                        }
                        mvwaddstr( dialog, thisRow, thisCol, "  " );
                        if ( qrModule & 1 ) {
                            wattroff( dialog, A_REVERSE );
                        }
                    }
                }
            }
            urlRow = qrStartRow + qrCode->width + 6;
            if ( urlRow < dialogHeight - 3 ) {
                mvwaddstr( dialog, urlRow, (dialogWidth - strlen(text)) / 2, text );
            }
            mvwaddstr( dialog, dialogHeight - 2, (dialogWidth - strlen(instructions)) / 2, instructions );
            wrefresh( dialog );
            wgetch( dialog );
            delwin( dialog );
        }
        QRcode_free( qrCode );
    }
}

#endif /* PLATFORM_NCURSES */
